enum actionTypes {
  INCREMENT = 'INCREMENT',
  INCREMENT_ASYNC = 'INCREMENT_ASYNC',
  DECREMENT = 'DECREMENT',
  FETCH_RANDOM_USERS = 'FETCH_RANDOM_USERS',
  SIGN_IN = 'SIGN_IN',
}

export { actionTypes };
